# Generated by Django 3.2.8 on 2022-01-27 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220127_0808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address2',
        ),
    ]
