# Generated by Django 3.2.8 on 2022-02-05 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_auto_20220127_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ref_code',
            field=models.CharField(max_length=255, null=True, verbose_name='ref_code'),
        ),
        migrations.AddField(
            model_name='rating',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='commerce.order', verbose_name='order'),
        ),
    ]
